In [4]:
import numpy as np

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
arr.max()

10

In [15]:
arr.min()

0

In [16]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [17]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [18]:
matrix = np.arange(1,26).reshape(5,5)

In [19]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [21]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [24]:
np.sum(matrix)

325

In [27]:
import pandas as pd
from numpy.random import randn

In [34]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
df

W         X         Y         Z
A -0.813323 -0.014427 -0.303266  2.458079
B  1.730964  0.617103  2.155125 -0.152507
C -0.071808 -0.014171 -0.215544  0.656087
D  0.750370  0.045803  0.076121 -1.240001
E  0.611242 -1.615103  0.244039  1.256137

In [30]:
df['W']

A    0.917478
B   -0.411921
C   -1.336929
D   -1.039723
E    0.014240
Name: W, dtype: float64

In [36]:
df['new'] = df['W'] + df['X']
df.head()

W         X         Y         Z       new
A -0.813323 -0.014427 -0.303266  2.458079 -0.827751
B  1.730964  0.617103  2.155125 -0.152507  2.348067
C -0.071808 -0.014171 -0.215544  0.656087 -0.085979
D  0.750370  0.045803  0.076121 -1.240001  0.796173
E  0.611242 -1.615103  0.244039  1.256137 -1.003860

In [37]:
df.drop('new', axis = 1 , inplace = True) # inplace true means not permanent remove, but save somewhere

In [38]:
df

W         X         Y         Z
A -0.813323 -0.014427 -0.303266  2.458079
B  1.730964  0.617103  2.155125 -0.152507
C -0.071808 -0.014171 -0.215544  0.656087
D  0.750370  0.045803  0.076121 -1.240001
E  0.611242 -1.615103  0.244039  1.256137

In [39]:
df.loc['C']

W   -0.071808
X   -0.014171
Y   -0.215544
Z    0.656087
Name: C, dtype: float64

In [40]:
df.loc[['A','B'],['X','Y']]

X         Y
A -0.014427 -0.303266
B  0.617103  2.155125

In [41]:
df[df['W']>0]

W         X         Y         Z
B  1.730964  0.617103  2.155125 -0.152507
D  0.750370  0.045803  0.076121 -1.240001
E  0.611242 -1.615103  0.244039  1.256137

In [42]:
#missing data
df.dropna(axis = 1)

W         X         Y         Z
A -0.813323 -0.014427 -0.303266  2.458079
B  1.730964  0.617103  2.155125 -0.152507
C -0.071808 -0.014171 -0.215544  0.656087
D  0.750370  0.045803  0.076121 -1.240001
E  0.611242 -1.615103  0.244039  1.256137

In [44]:
#df['A'].fillna(value=df['A'].mean())

In [45]:
df.groupby('X').count()

W  Y  Z
X                 
-1.615103  1  1  1
-0.014427  1  1  1
-0.014171  1  1  1
 0.045803  1  1  1
 0.617103  1  1  1

In [46]:
df['W'].value_counts()

 1.730964    1
 0.750370    1
-0.071808    1
-0.813323    1
 0.611242    1
Name: W, dtype: int64

In [47]:
df['W'].nunique()

5

In [48]:
df['W'].apply(lambda x:x*2)

A   -1.626646
B    3.461928
C   -0.143616
D    1.500741
E    1.222484
Name: W, dtype: float64